// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjZ_HQjyW0YF_MxgJ_KsEVnqLeYQWEsxQ',
    appId: '1:827607336219:web:81c36b5c9c6045056fbfbe',
    messagingSenderId: '827607336219',
    projectId: 'bigooit-tour',
    authDomain: 'bigooit-tour.firebaseapp.com',
    storageBucket: 'bigooit-tour.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3efjKILjoA9IBNdemMm6umJbQqndFd4E',
    appId: '1:827607336219:android:9cd9a4531e9b18f96fbfbe',
    messagingSenderId: '827607336219',
    projectId: 'bigooit-tour',
    storageBucket: 'bigooit-tour.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6PRnlW_9_x56sziTNNqbSXaLYn1HetSU',
    appId: '1:827607336219:ios:8489d62422a9b0616fbfbe',
    messagingSenderId: '827607336219',
    projectId: 'bigooit-tour',
    storageBucket: 'bigooit-tour.appspot.com',
    iosClientId: '827607336219-084bvbe2k797tpdjv1ohlkv1siit7e4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bigTour',
  );
}